trigger:
  mode: "rc"
  rc_topic: "/mavros/rc/in"
  rc_trigger_channel: 5
  rc_trigger_threshold: 1700

save_dir: "rc"

mcap_qos: "mcap_qos.yaml"

args:
  - -b
  - 1000000000          # ~1GB per file
  - --max-cache-size
  - 50000000            # 50MB buffer (memory saving)

topics:
  - /recording_status
  - /mavros/state
  - /mavros/rc/in