mcap_qos: mcap_qos.yaml
args:
  - -b
  - 1000000000          # ~1GB 마다 파일 분할
  - --max-cache-size
  - 50000000            # 50MB 버퍼 (메모리 절약)
topics:
  - /mavros/state
  - /livox/lidar
  - /livox/imu
  - /mavros/local_position/odom
  - /mavros/local_position/pose
  - /mavros/imu/data